// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition/ProtoMessage.proto

// Protobuf Java Version: 3.25.1
package org.wowtools.hppt.common.protobuf;

public final class ProtoMessage {
  private ProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BytesPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pojo.BytesPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes bytes = 1;</code>
     * @return The bytes.
     */
    com.google.protobuf.ByteString getBytes();

    /**
     * <code>int32 sessionId = 2;</code>
     * @return The sessionId.
     */
    int getSessionId();
  }
  /**
   * Protobuf type {@code pojo.BytesPb}
   */
  public static final class BytesPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pojo.BytesPb)
      BytesPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BytesPb.newBuilder() to construct.
    private BytesPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BytesPb() {
      bytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new BytesPb();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMessage.internal_static_pojo_BytesPb_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMessage.internal_static_pojo_BytesPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BytesPb.class, Builder.class);
    }

    public static final int BYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes = 1;</code>
     * @return The bytes.
     */
    @Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private int sessionId_ = 0;
    /**
     * <code>int32 sessionId = 2;</code>
     * @return The sessionId.
     */
    @Override
    public int getSessionId() {
      return sessionId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!bytes_.isEmpty()) {
        output.writeBytes(1, bytes_);
      }
      if (sessionId_ != 0) {
        output.writeInt32(2, sessionId_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!bytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, bytes_);
      }
      if (sessionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sessionId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BytesPb)) {
        return super.equals(obj);
      }
      BytesPb other = (BytesPb) obj;

      if (!getBytes()
          .equals(other.getBytes())) return false;
      if (getSessionId()
          != other.getSessionId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BytesPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BytesPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BytesPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BytesPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BytesPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BytesPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BytesPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BytesPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static BytesPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static BytesPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BytesPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BytesPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BytesPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pojo.BytesPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pojo.BytesPb)
        BytesPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMessage.internal_static_pojo_BytesPb_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMessage.internal_static_pojo_BytesPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BytesPb.class, Builder.class);
      }

      // Construct using org.wowtools.hppt.common.protobuf.ProtoMessage.BytesPb.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bytes_ = com.google.protobuf.ByteString.EMPTY;
        sessionId_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMessage.internal_static_pojo_BytesPb_descriptor;
      }

      @Override
      public BytesPb getDefaultInstanceForType() {
        return BytesPb.getDefaultInstance();
      }

      @Override
      public BytesPb build() {
        BytesPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BytesPb buildPartial() {
        BytesPb result = new BytesPb(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(BytesPb result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bytes_ = bytes_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sessionId_ = sessionId_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BytesPb) {
          return mergeFrom((BytesPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BytesPb other) {
        if (other == BytesPb.getDefaultInstance()) return this;
        if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
          setBytes(other.getBytes());
        }
        if (other.getSessionId() != 0) {
          setSessionId(other.getSessionId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                bytes_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                sessionId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes = 1;</code>
       * @return The bytes.
       */
      @Override
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>bytes bytes = 1;</code>
       * @param value The bytes to set.
       * @return This builder for chaining.
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        bytes_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }

      private int sessionId_ ;
      /**
       * <code>int32 sessionId = 2;</code>
       * @return The sessionId.
       */
      @Override
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int32 sessionId = 2;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(int value) {

        sessionId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sessionId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pojo.BytesPb)
    }

    // @@protoc_insertion_point(class_scope:pojo.BytesPb)
    private static final BytesPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BytesPb();
    }

    public static BytesPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BytesPb>
        PARSER = new com.google.protobuf.AbstractParser<BytesPb>() {
      @Override
      public BytesPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BytesPb> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BytesPb> getParserForType() {
      return PARSER;
    }

    @Override
    public BytesPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessagePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pojo.MessagePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    java.util.List<BytesPb>
        getBytesPbListList();
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    BytesPb getBytesPbList(int index);
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    int getBytesPbListCount();
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    java.util.List<? extends BytesPbOrBuilder>
        getBytesPbListOrBuilderList();
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    BytesPbOrBuilder getBytesPbListOrBuilder(
        int index);

    /**
     * <code>repeated string commandList = 2;</code>
     * @return A list containing the commandList.
     */
    java.util.List<String>
        getCommandListList();
    /**
     * <code>repeated string commandList = 2;</code>
     * @return The count of commandList.
     */
    int getCommandListCount();
    /**
     * <code>repeated string commandList = 2;</code>
     * @param index The index of the element to return.
     * @return The commandList at the given index.
     */
    String getCommandList(int index);
    /**
     * <code>repeated string commandList = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the commandList at the given index.
     */
    com.google.protobuf.ByteString
        getCommandListBytes(int index);
  }
  /**
   * Protobuf type {@code pojo.MessagePb}
   */
  public static final class MessagePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pojo.MessagePb)
      MessagePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessagePb.newBuilder() to construct.
    private MessagePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessagePb() {
      bytesPbList_ = java.util.Collections.emptyList();
      commandList_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessagePb();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMessage.internal_static_pojo_MessagePb_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMessage.internal_static_pojo_MessagePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagePb.class, Builder.class);
    }

    public static final int BYTESPBLIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<BytesPb> bytesPbList_;
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    @Override
    public java.util.List<BytesPb> getBytesPbListList() {
      return bytesPbList_;
    }
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    @Override
    public java.util.List<? extends BytesPbOrBuilder>
        getBytesPbListOrBuilderList() {
      return bytesPbList_;
    }
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    @Override
    public int getBytesPbListCount() {
      return bytesPbList_.size();
    }
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    @Override
    public BytesPb getBytesPbList(int index) {
      return bytesPbList_.get(index);
    }
    /**
     * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
     */
    @Override
    public BytesPbOrBuilder getBytesPbListOrBuilder(
        int index) {
      return bytesPbList_.get(index);
    }

    public static final int COMMANDLIST_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList commandList_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string commandList = 2;</code>
     * @return A list containing the commandList.
     */
    public com.google.protobuf.ProtocolStringList
        getCommandListList() {
      return commandList_;
    }
    /**
     * <code>repeated string commandList = 2;</code>
     * @return The count of commandList.
     */
    public int getCommandListCount() {
      return commandList_.size();
    }
    /**
     * <code>repeated string commandList = 2;</code>
     * @param index The index of the element to return.
     * @return The commandList at the given index.
     */
    public String getCommandList(int index) {
      return commandList_.get(index);
    }
    /**
     * <code>repeated string commandList = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the commandList at the given index.
     */
    public com.google.protobuf.ByteString
        getCommandListBytes(int index) {
      return commandList_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < bytesPbList_.size(); i++) {
        output.writeMessage(1, bytesPbList_.get(i));
      }
      for (int i = 0; i < commandList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commandList_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < bytesPbList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bytesPbList_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < commandList_.size(); i++) {
          dataSize += computeStringSizeNoTag(commandList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCommandListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagePb)) {
        return super.equals(obj);
      }
      MessagePb other = (MessagePb) obj;

      if (!getBytesPbListList()
          .equals(other.getBytesPbListList())) return false;
      if (!getCommandListList()
          .equals(other.getCommandListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBytesPbListCount() > 0) {
        hash = (37 * hash) + BYTESPBLIST_FIELD_NUMBER;
        hash = (53 * hash) + getBytesPbListList().hashCode();
      }
      if (getCommandListCount() > 0) {
        hash = (37 * hash) + COMMANDLIST_FIELD_NUMBER;
        hash = (53 * hash) + getCommandListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MessagePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MessagePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pojo.MessagePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pojo.MessagePb)
        MessagePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMessage.internal_static_pojo_MessagePb_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMessage.internal_static_pojo_MessagePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagePb.class, Builder.class);
      }

      // Construct using org.wowtools.hppt.common.protobuf.ProtoMessage.MessagePb.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (bytesPbListBuilder_ == null) {
          bytesPbList_ = java.util.Collections.emptyList();
        } else {
          bytesPbList_ = null;
          bytesPbListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        commandList_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMessage.internal_static_pojo_MessagePb_descriptor;
      }

      @Override
      public MessagePb getDefaultInstanceForType() {
        return MessagePb.getDefaultInstance();
      }

      @Override
      public MessagePb build() {
        MessagePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessagePb buildPartial() {
        MessagePb result = new MessagePb(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(MessagePb result) {
        if (bytesPbListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            bytesPbList_ = java.util.Collections.unmodifiableList(bytesPbList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.bytesPbList_ = bytesPbList_;
        } else {
          result.bytesPbList_ = bytesPbListBuilder_.build();
        }
      }

      private void buildPartial0(MessagePb result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          commandList_.makeImmutable();
          result.commandList_ = commandList_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagePb) {
          return mergeFrom((MessagePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagePb other) {
        if (other == MessagePb.getDefaultInstance()) return this;
        if (bytesPbListBuilder_ == null) {
          if (!other.bytesPbList_.isEmpty()) {
            if (bytesPbList_.isEmpty()) {
              bytesPbList_ = other.bytesPbList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBytesPbListIsMutable();
              bytesPbList_.addAll(other.bytesPbList_);
            }
            onChanged();
          }
        } else {
          if (!other.bytesPbList_.isEmpty()) {
            if (bytesPbListBuilder_.isEmpty()) {
              bytesPbListBuilder_.dispose();
              bytesPbListBuilder_ = null;
              bytesPbList_ = other.bytesPbList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bytesPbListBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBytesPbListFieldBuilder() : null;
            } else {
              bytesPbListBuilder_.addAllMessages(other.bytesPbList_);
            }
          }
        }
        if (!other.commandList_.isEmpty()) {
          if (commandList_.isEmpty()) {
            commandList_ = other.commandList_;
            bitField0_ |= 0x00000002;
          } else {
            ensureCommandListIsMutable();
            commandList_.addAll(other.commandList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                BytesPb m =
                    input.readMessage(
                        BytesPb.parser(),
                        extensionRegistry);
                if (bytesPbListBuilder_ == null) {
                  ensureBytesPbListIsMutable();
                  bytesPbList_.add(m);
                } else {
                  bytesPbListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                String s = input.readStringRequireUtf8();
                ensureCommandListIsMutable();
                commandList_.add(s);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<BytesPb> bytesPbList_ =
        java.util.Collections.emptyList();
      private void ensureBytesPbListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          bytesPbList_ = new java.util.ArrayList<BytesPb>(bytesPbList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          BytesPb, BytesPb.Builder, BytesPbOrBuilder> bytesPbListBuilder_;

      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public java.util.List<BytesPb> getBytesPbListList() {
        if (bytesPbListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bytesPbList_);
        } else {
          return bytesPbListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public int getBytesPbListCount() {
        if (bytesPbListBuilder_ == null) {
          return bytesPbList_.size();
        } else {
          return bytesPbListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public BytesPb getBytesPbList(int index) {
        if (bytesPbListBuilder_ == null) {
          return bytesPbList_.get(index);
        } else {
          return bytesPbListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder setBytesPbList(
          int index, BytesPb value) {
        if (bytesPbListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBytesPbListIsMutable();
          bytesPbList_.set(index, value);
          onChanged();
        } else {
          bytesPbListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder setBytesPbList(
          int index, BytesPb.Builder builderForValue) {
        if (bytesPbListBuilder_ == null) {
          ensureBytesPbListIsMutable();
          bytesPbList_.set(index, builderForValue.build());
          onChanged();
        } else {
          bytesPbListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder addBytesPbList(BytesPb value) {
        if (bytesPbListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBytesPbListIsMutable();
          bytesPbList_.add(value);
          onChanged();
        } else {
          bytesPbListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder addBytesPbList(
          int index, BytesPb value) {
        if (bytesPbListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBytesPbListIsMutable();
          bytesPbList_.add(index, value);
          onChanged();
        } else {
          bytesPbListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder addBytesPbList(
          BytesPb.Builder builderForValue) {
        if (bytesPbListBuilder_ == null) {
          ensureBytesPbListIsMutable();
          bytesPbList_.add(builderForValue.build());
          onChanged();
        } else {
          bytesPbListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder addBytesPbList(
          int index, BytesPb.Builder builderForValue) {
        if (bytesPbListBuilder_ == null) {
          ensureBytesPbListIsMutable();
          bytesPbList_.add(index, builderForValue.build());
          onChanged();
        } else {
          bytesPbListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder addAllBytesPbList(
          Iterable<? extends BytesPb> values) {
        if (bytesPbListBuilder_ == null) {
          ensureBytesPbListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bytesPbList_);
          onChanged();
        } else {
          bytesPbListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder clearBytesPbList() {
        if (bytesPbListBuilder_ == null) {
          bytesPbList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bytesPbListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public Builder removeBytesPbList(int index) {
        if (bytesPbListBuilder_ == null) {
          ensureBytesPbListIsMutable();
          bytesPbList_.remove(index);
          onChanged();
        } else {
          bytesPbListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public BytesPb.Builder getBytesPbListBuilder(
          int index) {
        return getBytesPbListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public BytesPbOrBuilder getBytesPbListOrBuilder(
          int index) {
        if (bytesPbListBuilder_ == null) {
          return bytesPbList_.get(index);  } else {
          return bytesPbListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public java.util.List<? extends BytesPbOrBuilder>
           getBytesPbListOrBuilderList() {
        if (bytesPbListBuilder_ != null) {
          return bytesPbListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bytesPbList_);
        }
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public BytesPb.Builder addBytesPbListBuilder() {
        return getBytesPbListFieldBuilder().addBuilder(
            BytesPb.getDefaultInstance());
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public BytesPb.Builder addBytesPbListBuilder(
          int index) {
        return getBytesPbListFieldBuilder().addBuilder(
            index, BytesPb.getDefaultInstance());
      }
      /**
       * <code>repeated .pojo.BytesPb bytesPbList = 1;</code>
       */
      public java.util.List<BytesPb.Builder>
           getBytesPbListBuilderList() {
        return getBytesPbListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          BytesPb, BytesPb.Builder, BytesPbOrBuilder>
          getBytesPbListFieldBuilder() {
        if (bytesPbListBuilder_ == null) {
          bytesPbListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              BytesPb, BytesPb.Builder, BytesPbOrBuilder>(
                  bytesPbList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          bytesPbList_ = null;
        }
        return bytesPbListBuilder_;
      }

      private com.google.protobuf.LazyStringArrayList commandList_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCommandListIsMutable() {
        if (!commandList_.isModifiable()) {
          commandList_ = new com.google.protobuf.LazyStringArrayList(commandList_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @return A list containing the commandList.
       */
      public com.google.protobuf.ProtocolStringList
          getCommandListList() {
        commandList_.makeImmutable();
        return commandList_;
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @return The count of commandList.
       */
      public int getCommandListCount() {
        return commandList_.size();
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @param index The index of the element to return.
       * @return The commandList at the given index.
       */
      public String getCommandList(int index) {
        return commandList_.get(index);
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the commandList at the given index.
       */
      public com.google.protobuf.ByteString
          getCommandListBytes(int index) {
        return commandList_.getByteString(index);
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @param index The index to set the value at.
       * @param value The commandList to set.
       * @return This builder for chaining.
       */
      public Builder setCommandList(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCommandListIsMutable();
        commandList_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @param value The commandList to add.
       * @return This builder for chaining.
       */
      public Builder addCommandList(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCommandListIsMutable();
        commandList_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @param values The commandList to add.
       * @return This builder for chaining.
       */
      public Builder addAllCommandList(
          Iterable<String> values) {
        ensureCommandListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commandList_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommandList() {
        commandList_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string commandList = 2;</code>
       * @param value The bytes of the commandList to add.
       * @return This builder for chaining.
       */
      public Builder addCommandListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCommandListIsMutable();
        commandList_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pojo.MessagePb)
    }

    // @@protoc_insertion_point(class_scope:pojo.MessagePb)
    private static final MessagePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagePb();
    }

    public static MessagePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessagePb>
        PARSER = new com.google.protobuf.AbstractParser<MessagePb>() {
      @Override
      public MessagePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessagePb> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessagePb> getParserForType() {
      return PARSER;
    }

    @Override
    public MessagePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pojo_BytesPb_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pojo_BytesPb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pojo_MessagePb_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pojo_MessagePb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035definition/ProtoMessage.proto\022\004pojo\"+\n" +
      "\007BytesPb\022\r\n\005bytes\030\001 \001(\014\022\021\n\tsessionId\030\002 \001" +
      "(\005\"D\n\tMessagePb\022\"\n\013bytesPbList\030\001 \003(\0132\r.p" +
      "ojo.BytesPb\022\023\n\013commandList\030\002 \003(\tB1\n!org." +
      "wowtools.hppt.common.protobufB\014ProtoMess" +
      "ageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pojo_BytesPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pojo_BytesPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pojo_BytesPb_descriptor,
        new String[] { "Bytes", "SessionId", });
    internal_static_pojo_MessagePb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pojo_MessagePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pojo_MessagePb_descriptor,
        new String[] { "BytesPbList", "CommandList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
